apiVersion: apps/v1 
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1 
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ordermanager/client
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
