apiVersion: apps/v1 
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1 
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ordermanager/server
        env:
        - name: OM_MONGODB_URL
          value: "mongo:27017/"
        - name: OM_MONGODB_NAME
          value: "order-manager-k8s"
        - name: OM_MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: OM_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: OM_SERVER_PORT
          value: "3001"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
